### PR TITLE
Better fallback

### PR DESCRIPTION
**Pull request by joshua-s**
Opens a new window if one of the following conditions are met:
- Web Activities are not supported
- Web Activities are supported, but the request returns an error

### CODE REVIEW

**Comment by dcoloma** [comment]
Thanks!

**Comment by joshua-s** [comment]
Sorry about the indentation issues. I fixed it on my branch, but the merge happened too quickly.

**Comment by dcoloma** [comment]
Feel free to issue a new PR, otherwise I'll take care of it. No worries.

**Comment by joshua-s** [comment]
Done! #14

**Pull request merged**
